window.PROJECTS_DATA = [
  {
    slug: "hannibal",
    title: "Hannibal",
    href: "projects/hannibal.html",
    description: "Educational Unity + Vuforia AR game for kids (6–12) about Carthage and Hannibal, with scan-based progression and mini-games.",
    thumbnail: "assets/media/hannibal/thumb2.jpg",
    thumbLabel: "UNITY",
    status: "Case Study",
    category: "education",
    pills: ["Unity", "AR", "Educational"],
    tags: ["unity", "ar", "ui"],
    showFeaturedRow: true,
    featuredOrder: 1,
    showHomeUnity: true,
    homeUnityOrder: 1,
    showProjectsPage: true,
    projectsOrder: 1
  },
  {
    slug: "djerba",
    title: "Djerba View AR",
    href: "projects/djerba.html",
    description: "Unity + Vuforia tourism AR app for Djerba: scan a companion book/cards to explore monuments in 3D and read local traditions.",
    thumbnail: "assets/media/jerbaview/logo-02.png",
    thumbLabel: "UNITY",
    status: "Published",
    category: "tourism",
    pills: ["Unity", "AR", "Mobile"],
    tags: ["unity", "ar"],
    showFeaturedRow: true,
    featuredOrder: 2,
    showHomeUnity: true,
    homeUnityOrder: 2,
    showProjectsPage: true,
    projectsOrder: 2
  },
  {
    slug: "ar-memory",
    title: "AR Memory",
    href: "projects/ar-memory.html",
    description: "Unity + Vuforia AR companion app where scanned postcards reveal interactive 3D historical monuments and photo capture.",
    thumbnail: "assets/media/armemory/image_2026-02-26_224140994.png",
    thumbLabel: "UNITY",
    status: "Prototype",
    category: "education",
    pills: ["Unity", "AR", "UI"],
    tags: ["unity", "ar", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUnity: true,
    homeUnityOrder: 3,
    showProjectsPage: true,
    projectsOrder: 3
  },
  {
    slug: "bartdo",
    title: "B.ART.DO",
    href: "projects/bartdo.html",
    description: "Guided AR museum visit prototype for Bardo artifacts with tutorial-led navigation and educational interaction.",
    thumbnail: "assets/media/bartdo/image_2026-02-26_224614953.png",
    thumbLabel: "UNITY",
    status: "Prototype",
    category: "education",
    pills: ["Unity", "AR", "Museum"],
    tags: ["unity", "ar", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUnity: true,
    homeUnityOrder: 4,
    showProjectsPage: true,
    projectsOrder: 4
  },
  {
    slug: "ue-interaction",
    title: "Blueprint Interaction Module",
    href: "projects/ue-interaction.html",
    description: "Reusable pickup / inspect / use module built for fast prototyping.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Module",
    category: "systems",
    pills: ["UE5", "Systems", "UX"],
    tags: ["ue5"],
    showFeaturedRow: true,
    featuredOrder: 3,
    showHomeUe: true,
    homeUeOrder: 1,
    showProjectsPage: true,
    projectsOrder: 5
  },
  {
    slug: "steamhouse-dialogue-ui",
    title: "Steam House — Dialogue System & UI/UX",
    href: "projects/steamhouse-dialogue-ui.html",
    description: "Behavior Tree-driven dialogue pipeline + typewriter UI, choices, quest/blackboard updates, and full menus.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE",
    status: "Case Study",
    category: "ui",
    pills: ["Behavior Trees", "Blueprint", "UMG"],
    tags: ["ue5", "ui"],
    showFeaturedRow: true,
    featuredOrder: 4,
    showProjectsPage: true,
    projectsOrder: 6
  },
  {
    slug: "ue-hud",
    title: "HUD Prototype",
    href: "projects/ue_hud.html",
    description: "Readability + feedback tests (prompts, notifications, HUD layout).",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Prototype",
    category: "ui",
    pills: ["UE5", "UI", "Prototype"],
    tags: ["ue5", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 3,
    showProjectsPage: true,
    projectsOrder: 7
  },
  {
    slug: "ue-lighting",
    title: "Lighting & Mood Study",
    href: "projects/ue_lighting.html",
    description: "Environment mood exploration: lighting, composition, atmosphere.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Study",
    category: "art",
    pills: ["UE5", "Lighting", "Mood"],
    tags: ["ue5"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 2,
    showProjectsPage: true,
    projectsOrder: 8
  },
  {
    slug: "ue-mechanics",
    title: "Mechanics Prototype",
    href: "projects/ue_mechanics.html",
    description: "Mechanics experiments to explore feel, responsiveness, player control.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Prototype",
    category: "gameplay",
    pills: ["UE5", "Gameplay", "Blueprint"],
    tags: ["ue5"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 4,
    showProjectsPage: true,
    projectsOrder: 9
  },
  {
    slug: "roadkill",
    title: "Roadkill",
    href: "projects/roadkill.html",
    description: "End-of-year 2.5D project built in UE5 with Blueprint gameplay systems, camera travelling logic, UI/UX flows, and cinematic typewriter sequences.",
    thumbnail: "assets/media/roadkill/shot-01.jpg",
    thumbLabel: "UE5",
    status: "In Progress",
    category: "gameplay",
    pills: ["UE5", "Blueprint", "UI/UX"],
    tags: ["ue5", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 5,
    showProjectsPage: true,
    projectsOrder: 10
  },
  {
    slug: "colors",
    title: "Colors — Prototype FPS",
    href: "projects/colors.html",
    description: "UE5 FPS prototype inspired by color-control gameplay: shoot color balloons and dynamically transform the environment.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Prototype",
    category: "gameplay",
    pills: ["UE5", "FPS", "Prototype"],
    tags: ["ue5", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 6,
    showProjectsPage: true,
    projectsOrder: 11
  }
];
