window.PROJECTS_DATA = [
  {
    slug: "coffre-fort",
    title: "Coffre Fort — UX/UI Case Study",
    href: "projects/coffre-fort.html",
    description: "Secure document portal for lawyers and their clients: research, personas, journey maps, wireframes, UI kit and high-fidelity desktop + mobile screens.",
    thumbnail: "assets/media/coffre-fort/card-thumb.webp",
    thumbLabel: "FIGMA",
    status: "Case Study",
    category: "ux",
    pills: ["UX Research", "UI Design", "Design System"],
    tags: ["ui"],
    featuredOrder: 1,
    showFeaturedRow: true,
    showHomeUnity: false,
    showHomeUe: false,
    showProjectsPage: true,
    projectsOrder: 0,
    showCarousel: true,
    carouselOrder: 1,
    carouselLabel: "Case Study",
    carouselTitle: "Coffre Fort — UX/UI",
    carouselText: "Secure document portal for lawyers and clients: research, journeys, wireframes, UI kit and hi-fi screens.",
    carouselImage: "assets/media/coffre-fort/cover.webp"
  },
  {
    slug: "hannibal",
    title: "Hannibal",
    href: "projects/hannibal.html",
    description: "Educational Unity + Vuforia AR game for kids (6–12) about Carthage and Hannibal, with scan-based progression and mini-games.",
    thumbnail: "assets/media/hannibal/card-thumb.webp",
    thumbLabel: "UNITY",
    status: "Case Study",
    category: "education",
    pills: ["Unity", "AR", "Educational"],
    tags: ["unity", "ar", "ui"],
    showFeaturedRow: false,
    featuredOrder: 1,
    showHomeUnity: true,
    homeUnityOrder: 1,
    showProjectsPage: true,
    projectsOrder: 1,
    showCarousel: true,
    carouselOrder: 2,
    carouselLabel: "Featured",
    carouselTitle: "Hannibal (Unity AR)",
    carouselText: "Educational AR for kids (6–12): UI, mechanics, AR modules, audio."
  },
  {
    slug: "djerba",
    title: "Djerba View AR",
    href: "projects/djerba.html",
    description: "Unity + Vuforia tourism AR app for Djerba: scan a companion book/cards to explore monuments in 3D and read local traditions.",
    thumbnail: "assets/media/jerbaview/card-thumb.webp",
    thumbFit: "contain",
    thumbBg: "linear-gradient(160deg,#bfe6ff,#5fb3f0)",
    thumbLabel: "UNITY",
    status: "Published",
    category: "tourism",
    pills: ["Unity", "AR", "Mobile"],
    tags: ["unity", "ar"],
    showFeaturedRow: false,
    featuredOrder: 3,
    showHomeUnity: true,
    homeUnityOrder: 2,
    showProjectsPage: true,
    projectsOrder: 2
  },
  {
    slug: "ar-memory",
    title: "AR Memory",
    href: "projects/ar-memory.html",
    description: "Unity + Vuforia AR companion app where scanned postcards reveal interactive 3D historical monuments and photo capture.",
    thumbnail: "assets/media/armemory/card-thumb.webp",
    thumbFit: "contain",
    thumbBg: "#ffffff",
    thumbLabel: "UNITY",
    status: "Prototype",
    category: "education",
    pills: ["Unity", "AR", "UI"],
    tags: ["unity", "ar", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUnity: true,
    homeUnityOrder: 3,
    showProjectsPage: true,
    projectsOrder: 3,
    showCarousel: true,
    carouselOrder: 5,
    carouselLabel: "Unity AR",
    carouselTitle: "AR Memory",
    carouselText: "Postcards come to life: clean UI flow + AR trigger moments.",
    carouselImage: "assets/media/armemory/20260226-1157-02-1061775-poster.webp"
  },
  {
    slug: "bartdo",
    title: "B.ART.DO",
    href: "projects/bartdo.html",
    description: "Guided AR museum visit prototype for Bardo artifacts with tutorial-led navigation and educational interaction.",
    thumbnail: "assets/media/bartdo/card-thumb.webp",
    thumbLabel: "UNITY",
    status: "Prototype",
    category: "education",
    pills: ["Unity", "AR", "Museum"],
    tags: ["unity", "ar", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUnity: true,
    homeUnityOrder: 4,
    showProjectsPage: true,
    projectsOrder: 4
  },
  {
    slug: "ue-interaction",
    title: "Blueprint Interaction Module",
    href: "projects/ue-interaction.html",
    description: "Reusable pickup / inspect / use module built for fast prototyping.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Module",
    category: "systems",
    pills: ["UE5", "Systems", "UX"],
    tags: ["ue5"],
    showFeaturedRow: false,
    featuredOrder: 3,
    showHomeUe: false,
    homeUeOrder: 1,
    showProjectsPage: false,
    projectsOrder: 5
  },
  {
    slug: "steamhouse-dialogue-ui",
    title: "Steam House — Dialogue System & UI/UX",
    href: "projects/steamhouse-dialogue-ui.html",
    description: "Behavior Tree-driven dialogue pipeline + typewriter UI, choices, quest/blackboard updates, and full menus.",
    thumbnail: "assets/media/steamhouse/card-thumb.webp",
    thumbLabel: "UE5",
    status: "Case Study",
    category: "ui",
    pills: ["Behavior Trees", "Blueprint", "UMG"],
    tags: ["ue5", "ui"],
    showFeaturedRow: true,
    featuredOrder: 2,
    showHomeUe: true,
    showProjectsPage: true,
    projectsOrder: 6,
    showCarousel: true,
    carouselOrder: 3,
    carouselLabel: "Case Study",
    carouselTitle: "Steam House (UE5) — Dialogue & UI",
    carouselText: "Behavior Tree-driven dialogue + typewriter UI, choices, and full menu implementation."
  },
  {
    slug: "ue-hud",
    title: "HUD Prototype",
    href: "projects/ue_hud.html",
    description: "Readability + feedback tests (prompts, notifications, HUD layout).",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Prototype",
    category: "ui",
    pills: ["UE5", "UI", "Prototype"],
    tags: ["ue5", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: false,
    homeUeOrder: 3,
    showProjectsPage: false,
    projectsOrder: 7
  },
  {
    slug: "ue-lighting",
    title: "Lighting & Mood Study",
    href: "projects/ue_lighting.html",
    description: "Environment mood exploration: lighting, composition, atmosphere.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Study",
    category: "art",
    pills: ["UE5", "Lighting", "Mood"],
    tags: ["ue5"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: false,
    homeUeOrder: 2,
    showProjectsPage: false,
    projectsOrder: 8
  },
  {
    slug: "ue-mechanics",
    title: "Mechanics Prototype",
    href: "projects/ue_mechanics.html",
    description: "Mechanics experiments to explore feel, responsiveness, player control.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Prototype",
    category: "gameplay",
    pills: ["UE5", "Gameplay", "Blueprint"],
    tags: ["ue5"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: false,
    homeUeOrder: 4,
    showProjectsPage: false,
    projectsOrder: 9
  },
  {
    slug: "roadkill",
    title: "Roadkill",
    href: "projects/roadkill.html",
    description: "End-of-year 2.5D project built in UE5 with Blueprint gameplay systems, camera travelling logic, UI/UX flows, and cinematic typewriter sequences.",
    thumbnail: "assets/media/roadkill/card-thumb.webp",
    thumbFit: "contain",
    thumbBg: "radial-gradient(circle at 50% 40%,#2a2a33,#0b0b0f 70%)",
    thumbLabel: "UE5",
    status: "In Progress",
    category: "gameplay",
    pills: ["UE5", "Blueprint", "UI/UX"],
    tags: ["ue5", "ui"],
    showFeaturedRow: true,
    featuredOrder: 3,
    showHomeUe: true,
    homeUeOrder: 5,
    showProjectsPage: true,
    projectsOrder: 10,
    showCarousel: true,
    carouselOrder: 4,
    carouselLabel: "UE5 Project",
    carouselTitle: "Roadkill",
    carouselText: "2.5D game: Blueprint gameplay, camera travelling, UI/UX flows and cinematic typewriter sequences.",
    carouselImage: "assets/media/roadkill/shot-05.webp"
  },
  {
    slug: "colors",
    title: "Colors — Prototype FPS",
    href: "projects/colors.html",
    description: "UE5 FPS prototype inspired by color-control gameplay: shoot color balloons and dynamically transform the environment.",
    thumbnail: "assets/media/color/card-thumb.webp",
    thumbLabel: "UE5",
    status: "Prototype",
    category: "gameplay",
    pills: ["UE5", "FPS", "Prototype"],
    tags: ["ue5", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 6,
    showProjectsPage: true,
    projectsOrder: 11
  }
];
