window.PROJECTS_DATA = [
  {
    slug: "hannibal",
    title: "Hannibal",
    href: "projects/hannibal.html",
    description: "Educational AR experience for kids (6–12). UI, mechanics, AR modules, audio.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UNITY",
    status: "Case Study",
    category: "education",
    pills: ["Unity", "AR", "UI/UX"],
    tags: ["unity", "ar", "ui"],
    showFeaturedRow: true,
    featuredOrder: 1,
    showHomeUnity: true,
    homeUnityOrder: 1,
    showProjectsPage: true,
    projectsOrder: 1
  },
  {
    slug: "djerba",
    title: "Djerba View AR",
    href: "projects/djerba.html",
    description: "Tourism-focused AR app. UI + 3D + AR integration + gallery module.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UNITY",
    status: "Published",
    category: "tourism",
    pills: ["Unity", "AR", "Mobile"],
    tags: ["unity", "ar"],
    showFeaturedRow: true,
    featuredOrder: 2,
    showHomeUnity: true,
    homeUnityOrder: 2,
    showProjectsPage: true,
    projectsOrder: 2
  },
  {
    slug: "ar-memory",
    title: "AR Memory",
    href: "projects/ar-memory.html",
    description: "Postcards come to life in AR. Clean UI flow + AR trigger moments.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UNITY",
    status: "Prototype",
    category: "education",
    pills: ["Unity", "AR", "UI"],
    tags: ["unity", "ar", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUnity: true,
    homeUnityOrder: 3,
    showProjectsPage: true,
    projectsOrder: 3
  },
  {
    slug: "ue-interaction",
    title: "Blueprint Interaction Module",
    href: "projects/ue-interaction.html",
    description: "Reusable pickup / inspect / use module built for fast prototyping.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Module",
    category: "systems",
    pills: ["UE5", "Systems", "UX"],
    tags: ["ue5"],
    showFeaturedRow: true,
    featuredOrder: 3,
    showHomeUe: true,
    homeUeOrder: 1,
    showProjectsPage: true,
    projectsOrder: 7
  },
  {
    slug: "steamhouse-dialogue-ui",
    title: "Steam House — Dialogue System & UI/UX",
    href: "projects/steamhouse-dialogue-ui.html",
    description: "Behavior Tree-driven dialogue pipeline + typewriter UI, choices, quest/blackboard updates, and full menus.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE",
    status: "Case Study",
    category: "ui",
    pills: ["Behavior Trees", "Blueprint", "UMG"],
    tags: ["ue5", "ui"],
    showFeaturedRow: true,
    featuredOrder: 4,
    showProjectsPage: false,
    projectsOrder: 99
  },
  {
    slug: "ue-hud",
    title: "HUD Prototype",
    href: "projects/ue_hud.html",
    description: "Readability + feedback tests (prompts, notifications, HUD layout).",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Prototype",
    category: "ui",
    pills: ["UE5", "UI", "Prototype"],
    tags: ["ue5", "ui"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 3,
    showProjectsPage: true,
    projectsOrder: 4
  },
  {
    slug: "ue-lighting",
    title: "Lighting & Mood Study",
    href: "projects/ue_lighting.html",
    description: "Environment mood exploration: lighting, composition, atmosphere.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Study",
    category: "art",
    pills: ["UE5", "Lighting", "Mood"],
    tags: ["ue5"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 2,
    showProjectsPage: true,
    projectsOrder: 5
  },
  {
    slug: "ue-mechanics",
    title: "Mechanics Prototype",
    href: "projects/ue_mechanics.html",
    description: "Mechanics experiments to explore feel, responsiveness, player control.",
    thumbnail: "assets/icons/card-thumbnail-placeholder.svg",
    thumbLabel: "UE5",
    status: "Prototype",
    category: "gameplay",
    pills: ["UE5", "Gameplay", "Blueprint"],
    tags: ["ue5"],
    showFeaturedRow: false,
    featuredOrder: 99,
    showHomeUe: true,
    homeUeOrder: 4,
    showProjectsPage: true,
    projectsOrder: 6
  }
];
